name: OpenTofu Tests

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "**.md"

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    uses: osinfra-io/pt-techne-opentofu-workflows/.github/workflows/test.yml@36354e7cc82aa4b1208cb31b1fd344828539a347 # v0.3.9
    if: github.actor != 'dependabot[bot]'
    with:
      opentofu_version: ${{ vars.OPENTOFU_VERSION }}
