name: OpenTofu Tests

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "**.md"

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    uses: osinfra-io/pt-techne-opentofu-workflows/.github/workflows/test.yml@8af74f7c3eee27cc3751fd92d2b22db45d6b40d5 # v0.3.7
    if: github.actor != 'dependabot[bot]'
    with:
      opentofu_version: ${{ vars.OPENTOFU_VERSION }}
