name: OpenTofu Tests

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "**.md"

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    uses: osinfra-io/pt-techne-opentofu-workflows/.github/workflows/test.yml@5f1739a6197fab1022f433ee526e7647ab4fae6d # v0.3.5
    if: github.actor != 'dependabot[bot]'
    with:
      opentofu_version: ${{ vars.OPENTOFU_VERSION }}
